# define  shifr_number_array_pub( M ) ((M)->HRDG)
# define  shifr_streambuf_file_pub( M ) ((M)->oRmq)
# define  shifr_streambuf_buf_pub( M ) ((M)->FmoX)
# define  shifr_streambuf_bufbitsize_pub( M ) ((M)->XUvM)
# define  shifr_streambuf_bytecount_pub( M ) ((M)->D6h7)
